- name: Delete {{COMPONENT}} Directory
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Create {{COMPONENT}} Directory
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory

- name: Download and Unarchive {{COMPONENT}} on remote machine
  unarchive:
    src: "{{ARTIFACT_ZIP_URL}}"
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes

