- name: Setup OS Pre-requisites
  include_tasks: os.yml

- name: Install NodeJS Packages
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Create Application User
  user:
    name: roboshop

- name: Download Artifacts
  include_tasks:  download-with-az-artifacts.yml

- name: Download NodeJS dependencies
  shell: npm install
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Setup SystemD Service
  include_tasks: systemd-setup.yml

