- name: Install NodeJS Packages
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Create Application User
  user:
    name: roboshop

- name: Download Artifacts
  include_tasks: download-with-curl.yml

