- name: Setup OS Pre-requisites
  include_tasks: os.yml

- name: Install NodeJS Packages
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Create Application User
  user:
    name: roboshop

- name: Download Artifacts
  include_tasks: download-with-curl.yml

- name: Download NodeJS dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop

- name: Setup SystemD Service
  include_tasks: systemd-setup.yml

