- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Delete old content
  file:
    path: /usr/share/nginx
    state: absent

- name: Create content directory
  file:
    path: /usr/share/nginx
    state: directory

- name: Download and Unarchive {{COMPONENT}} on remote machine
  unarchive:
    src: "{{ARTIFACT_ZIP_URL}}"
    dest: /usr/share/nginx
    remote_src: yes

- name: Rename content directory
  shell: mv /usr/share/nginx/static /usr/share/nginx/html

- name: Update Nginx Configuration
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx

- name: Start Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started
