- name: Demo on variables
  hosts: all
  vars:
    URL: vars.sample.com
  tasks:
    - name: Print the variable
      ansible.builtin.debug:
        msg: Hello {{ URL }}

    - name: Print the variable again
      ansible.builtin.debug:
        msg: Hello {{ URL }}
