- name: Demo on variables
  hosts: all
  vars:
    URL: vars.sample.com
  tasks:
    - name: Print the variable
      ansible.builtin.debug:
        msg: Hello {{ URL }}

    - name: Print the variable again
      ansible.builtin.debug:
        msg: Hello {{ URL }}

    - name: Print Local variable
      ansible.builtin.debug:
        msg: Hello {{ URL }}
      vars:
        URL: tasks.google.com

## Observation:
# 1. vars declared on Play level can be accessed by any task in the play.
# 2. One play variables cannot be accessed by another play by default.
# 3. Local variables are having higher precedence than global variables.

# Some times we need to load the variables from a file.

- name: Demo on variables from files
  hosts: all
  vars_files:
    - vars.yml
  vars:
    URL: vars.sample.com
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: Helloo {{ URL }}
