- name: Demo on Run time declaring variables
  hosts: all
  tasks:
    - name: Run a shell command
      ansible.builtin.shell: uname
      register: OUT

    - name: Print OUT variable
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"

    ## Some times we need to store the output in a standard variable and use across the play, Such cases we store the variable in a standard name.
    - name: Declare variable
      ansible.builtin.set_fact:
        UNAME: "{{OUT.stdout}}"

    - name: Print UNAME
      ansible.builtin.debug:
        msg: "{{UNAME}}"

