- name: Demo on conditions
  hosts: all
  tasks:
    - name: Print OS name
      debug:
        msg: "OS HOSTNAME NAME = {{ansible_fqdn}}"
      when: ansible_os_family == "RedHat"
    - name: Print OS name
      debug:
        msg: "OS HOSTNAME NAME = {{ansible_fqdn}}"
      when: ansible_os_family == "Ubuntu"
