- name: Demo on templates
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: COpy sample.txt file
      copy:
        src: sample.txt
        dest: /tmp/sample.txt

    - name: Copy smaple.txt template
      template:
        src: sample.txt
        dest: /tmp/template.txt
