- name: Demo on tags
  hosts: localhost
  tasks:
    - name: DevOps Course
      debug:
        msg: "Welcome to DevOps"
      tags:
        - DevOps
    - name: AWS Course
      debug:
        msg: "Welcome to AWS"
      tags:
        - AWS

