- name: Setup RoboShop Project
  hosts: all
  vars:
    DOMAIN: devopsb53.tk
  become: yes
  # Become is nothing but a sudo in CLI, Also this become can be used in task level also
  tasks:
    - name: Load Cart Role
      import_role:
        name: cart
      when: component == "cart"
      tags:
        - cart

    - name: Load Catalogue Role
      import_role:
        name: catalogue
      when: component == "catalogue"
      tags:
        - catalogue

    - name: Load User Role
      import_role:
        name: user
      when: component == "user"
      tags:
        - user

    - name: Load Shipping Role
      import_role:
        name: shipping
      when: component == "shipping"
      tags:
        - shipping

#    - name: Load Payment Role
#      import_role:
#        name: payment
#      when: component == "payment"
#
#    - name: Load Frontend Role
#      import_role:
#        name: frontend
#      when: component == "frontend"
