- name: Copy MySQL repo file
  template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove MariaDB Libs
  yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL
  yum:
    name: mysql-community-server
    state: present

- name: Start MySQL
  systemd:
    name: mysqld
    state: started
    enabled: yes

