- name: Include Common Role for OS Prereqs
  include_role:
    name: common
    tasks_from: os

- name: COpy Mongo repo file
  template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

